"""empty message

Revision ID: 1c9cc6279908
Revises: 46fdcd0effa6
Create Date: 2021-01-29 06:18:40.506625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1c9cc6279908'
down_revision = '46fdcd0effa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ctq_s', sqlite.JSON(), nullable=True))
    op.drop_column('user', 'ctq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ctq', sqlite.JSON(), nullable=True))
    op.drop_column('user', 'ctq_s')
    # ### end Alembic commands ###
