"""empty message

Revision ID: 44051b07f14a
Revises: d6a692fcb2b3
Create Date: 2021-03-07 12:20:13.873046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44051b07f14a'
down_revision = 'd6a692fcb2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    # ### end Alembic commands ###
