"""empty message

Revision ID: 46fdcd0effa6
Revises: 63b3603f6679
Create Date: 2021-01-29 06:03:01.069391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '46fdcd0effa6'
down_revision = '63b3603f6679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CTQ')
    op.add_column('listing', sa.Column('rating', sqlite.JSON(), nullable=True))
    op.add_column('user', sa.Column('ctq', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ctq')
    op.drop_column('listing', 'rating')
    op.create_table('CTQ',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ctq_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.Column('listing_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ctq_name')
    )
    # ### end Alembic commands ###
