"""empty message

Revision ID: 63b3603f6679
Revises: 9c3fa6b4dd3e
Create Date: 2021-01-27 18:10:10.106290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b3603f6679'
down_revision = '9c3fa6b4dd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CTQ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctq_name', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ctq_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CTQ')
    # ### end Alembic commands ###
