"""empty message

Revision ID: dee7c23a4532
Revises: 8cd8dff58068
Create Date: 2021-02-14 20:21:44.195814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee7c23a4532'
down_revision = '8cd8dff58068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'total')
    # ### end Alembic commands ###
